### ISSUE TITLE
Swift usage 

### ISSUE THREAD

**Issue by maasim94** [netguru/ngrvalidator#12]
can we use this project in swift?
if yes, should i make need to make models in objc-C to validate?? or i can make then in swift and by importing library in bridging header

**Comment by PatrykKaczmarek** [comment]
**Short answer:**
Yes. You can use it in swift as well but in limited scope.

**Long answer:**
Currently library is Objective-C oriented so you cannot use it in _swifty_ way. Unfortunately your models have to inherit from `NSObject` because `NGRValidator` uses `NSObject` API  under the hood. 

You can easily define model in old way:

```
class User: NSObject {
    let email: String

    init(email: String) {
        self.email = email
    }

    func validate() -> NSError? {
        var error: NSError?
        NGRValidator.validateModel(self, error: &error, delegate: nil) { () -> [AnyObject]! in
            [NGRPropertyValidator(property: "email").is.required().to.have.syntax(NGRSyntax.Email)]
        }
        return error
    }
}
```

and calling validate function will work as follows:

```
let user = User(email: "foo")
print(user.validate()) // prints "Email has invalid syntax." error
```

if you do not mind (but you should) that models wouldn't be value typed, you can use it as above. If you want to take an advantage of error handling in swift you can wrap validation in other function:

```
func validateThatThrows() throws {
    var error: NSError?
    NGRValidator.validateModel(self, error: &error, delegate: nil) { () -> [AnyObject]! in
        [NGRPropertyValidator(property: "email").required().to.have.syntax(NGRSyntax.Email)]
    }
    if let error = error {
        throw error
    }
}
```

To use `NGRValidator` in swift, just add pod in your podfile and `import NGRValidator` module in file where you want to use it. If you aren't using CocoaPods, you should add `NGRValidator.h` to bridging header.

**Comment by maasim94** [comment]
thanks for detailed explain :) 👍
